# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import travels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('date_from', models.DateField(validators=[travels.models.date_after_now])),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.BooleanField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(through='travels.User_Trip', to='login.User'),
        ),
    ]
