# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[login.models.validate_word])),
                ('username', models.CharField(max_length=25, unique=True, validators=[login.models.validate_word])),
                ('password', models.CharField(max_length=125, validators=[login.models.validate_password])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
